version: 2
updates:
- package-ecosystem: swift
  directory: /
  schedule:
    interval: weekly
  groups:
    swift-deps:
      patterns:
      - '*'
    swift-security:
      applies-to: security-updates
      patterns:
      - '*'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  groups:
    github-actions-deps:
      patterns:
      - '*'
    github-actions-security:
      applies-to: security-updates
      patterns:
      - '*'